# Site wide configuration

title: V. Elenhaupt Blog
locale: en_US
url: http://veelenga.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Vitalii Elenhaupt
  avatar: https://s.gravatar.com/avatar/fb7415aea80a8fa64f7427086eedb6ee?s=80
  bio: "I enjoy programming and taking pictures. Love <b>learning</b>, <b>helping</b> other people and <b>seeing</b> them learn."
  email: velenhaupt@gmail.com
  disqus-shortname: veelenga
  twitter: veelenga
  #facebook: #username
  google:
    analytics: true
  #bing-verify:
  github: veelenga
  stackoverflow: 1586762/vitalii-elenhaupt
  #linkedin: #username
  #xing: #username
  #instagram: #username
  #lastfm: #username
  #tumblr: #username
  #pinterest: #username
  #foursquare: #username
  #steam: #username
  #dribbble: #username
  #youtube: #username
  #soundcloud: #username
  #weibo: #username
  #flickr: #username
  #codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
